import { getPool } from "../../../../lib/db.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// DELETE /api/invoices/cleanup - removes all pending invoices to non-real customers
export async function DELETE() {
  try {
    const pool = getPool();
    
    // Delete all pending invoices that have company names in parentheses (like "Anthropic (San Francisco, US)")
    // These are fake leads generated by the sales agent
    const { rowCount } = await pool.query(
      "DELETE FROM invoices WHERE status IN ('pending', 'overdue') AND customer LIKE '%(%'"
    );

    // Get remaining count
    const { rows } = await pool.query("SELECT COUNT(*) as count FROM invoices WHERE status = 'pending'");

    return Response.json({
      success: true,
      deleted: rowCount,
      remainingPending: Number(rows[0].count),
      message: `Deleted ${rowCount} fake invoices. ${rows[0].count} real invoices remain.`,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}
